name: Build, Scan, Publish and Deploy node-mongo application
"on":
    push: 
        branches:
          - main
    workflow_dispatch:

jobs:
    build-scan-audit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout github code
              uses: actions/checkout@v6
              
            - name: Install node application
              uses: actions/setup-node@v5
              with:
                node-version: "24.x"

            - name: Install node packages
              run: npm ci

            - name: Scan installed node packages
              run: npm audit --audit-level=high

            - name: Lint the application
              run: npm run lint
            
            - name: Format the application
              run: npm run format:check

    build-scan-docker-image:
        runs-on: ubuntu-latest
        needs: build-scan-audit
        steps:
          - name: Checkout the code to use Dockerfile
            uses: actions/checkout@v6

          - name: Build docker image
            run: |
              docker build --pull -t ${{ secrets.DOCKERHUB_USERNAME }}/node-mongo-secure-img:${{ github.sha }} .

          - name: Scan docker image
            uses: aquasecurity/trivy-action@0.22.0
            with:
              image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/node-mongo-secure-img:${{ github.sha }}
              severity: CRITICAL,HIGH
              exit-code: 1
              ignore-unfixed: true
              scanners: vuln
              vuln-type: os,library
          