name: Build, Scan, Publish and Deploy node-mongo application
"on":
    push: 
        branches:
          - main
    workflow_dispatch:

jobs:
    build-scan-audit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout github code
              uses: actions/checkout@v6
              
            - name: Install node application
              uses: actions/setup-node@v5
              with:
                node-version: "24.x"

            - name: Install node packages
              run: npm ci

            - name: Scan installed node packages
              run: npm audit --audit-level=high

            - name: Lint the application
              run: npm run lint
            
            - name: Format the application
              run: npm run format:check
    
