name: Build, Scan, Publish and Deploy node-mongo application
"on":
    push: 
        branches:
          - main
    workflow_dispatch:

jobs:
    build-scan-audit:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout github code
              uses: actions/checkout@v6
              
            - name: Install node application
              uses: actions/setup-node@v5
              with:
                node-version: "24.x"
                cache: "npm"

            - name: Install node packages
              run: npm ci

            - name: Scan installed node packages
              run: npm audit --audit-level=high

            - name: Lint the application
              run: npm run lint
            
            - name: Format the application
              run: npm run format:check

    build-scan-push-docker-image:
        runs-on: ubuntu-latest
        needs: build-scan-audit
        steps:
          - name: Checkout the code to use Dockerfile
            uses: actions/checkout@v6

          - name: Build docker image
            run: |
              docker build --pull \
              -t ${{ secrets.DOCKERHUB_USERNAME }}/node-mongo-secure-img:${{ github.sha }} \
              -t ${{ secrets.DOCKERHUB_USERNAME }}/node-mongo-secure-img:latest \
              .


          - name: Scan docker image
            uses: aquasecurity/trivy-action@0.22.0
            with:
              image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/node-mongo-secure-img:${{ github.sha }}
              severity: CRITICAL,HIGH
              exit-code: 1
              ignore-unfixed: true
              trivyignores: .trivyignore

          - name: Docker login
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
          - name: Docker push image
            run: |
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-mongo-secure-img:${{ github.sha }}
              docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-mongo-secure-img:latest

    deploy-app-to-ec2:
        runs-on: ubuntu-latest
        needs: build-scan-push-docker-image
        steps:
          - name: SSH into ec2 instance
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.EC2_HOST }}  # public ip
              username: ${{ secrets.EC2_USER }}  # server username
              key: ${{ secrets.EC2_SSH_KEY }}  # .pem key
              script: |
                echo "EC2 instance connected"
                docker pull ${{ secrets.DOCKERHUB_USERNAME }}/node-mongo-secure-img:${{ github.sha }}

                docker stop node-mongo-app1 node-mongo-app2 || true
                docker rm node-mongo-app1 node-mongo-app2 || true

                docker run -d --restart=always -p 9001:9000 -e PORT=${{ secrets.PORT }} -e MONGODB_URI=${{ secrets.MONGODB_URI }} --name node-mongo-app1 ${{ secrets.DOCKERHUB_USERNAME }}/node-mongo-secure-img:${{ github.sha }}

                docker run -d --restart=always -p 9002:9000 -e PORT=${{ secrets.PORT }} -e MONGODB_URI=${{ secrets.MONGODB_URI }} --name node-mongo-app2 ${{ secrets.DOCKERHUB_USERNAME }}/node-mongo-secure-img:${{ github.sha }}

                echo "Cleaning unused Docker images"
                docker image prune -af || true
          